spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:    config:      server: 
        git:          uri: https://github.com/rajasekharreddybusireddy/cloud-config-server
          
server:  port: 8084
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true    
  instance:
    hostname: localhost