server:
  port: 8082

spring:
  cloud:    gateway:      routes:      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:        - Path=/order/**
        filters:        - name: CircuitBreaker
          args:            name: order-service
            fallbackuri: forward:/orderServiceFallback            
      - id: payment-service
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payment/**  
        filters:
        - name: CircuitBreaker
          args:
            name: payment-service
            fallbackuri: forward:/paymentServiceFallback         
  application:
    name: CLOUD-GATEWAY
    
    
    
management:  endpoints:    web:      exposure:        include: hystrix.stream
        
        
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000     
      